spring:
  application:
    name: spring-auth

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  token-prefix: "Bearer "
  authorization-header: "Authorization"
  refresh-header: "Refresh"